### ISSUE TITLE
add a valid `project` table to the `pyproject.toml`

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo-app#21]
Currently there is no `project` table to the `pyproject.toml`, this prevents from running `uv run manage.py check` for example.

Some minimal required metadata could be added to the `project` part of the `pyproject.toml`: 
```toml
[project]
name = "rdmo-app"
version = "0"
requires-python = ">=3.9,<3.13"
```
